# Generated by Django 3.1.7 on 2021-03-06 09:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positon', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('date_started', models.DateField(default=datetime.datetime(2021, 3, 6, 9, 13, 21, 119624, tzinfo=utc))),
                ('date_ended', models.DateField(default=datetime.datetime(2021, 3, 6, 9, 13, 21, 119624, tzinfo=utc))),
                ('desc', models.TextField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positon', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('date_started', models.DateField(default=datetime.datetime(2021, 3, 6, 9, 13, 21, 119624, tzinfo=utc))),
                ('date_ended', models.DateField(default=datetime.datetime(2021, 3, 6, 9, 13, 21, 119624, tzinfo=utc))),
                ('desc', models.TextField(max_length=5000)),
            ],
        ),
    ]
