# Generated by Django 3.1.7 on 2021-03-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_education_professionalskills_workexperience'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalskills',
            name='color',
            field=models.CharField(choices=[('blue', 'blue'), ('green', 'green')], default='bleu', max_length=50),
        ),
        migrations.AlterField(
            model_name='education',
            name='date_ended',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='education',
            name='date_started',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='date_ended',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='date_started',
            field=models.DateField(),
        ),
    ]
