# Generated by Django 3.1.7 on 2021-03-06 15:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_auto_20210306_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='date_ended',
            field=models.DateField(default=datetime.date(2021, 3, 6), null=True),
        ),
    ]
