# Generated by Django 3.1.7 on 2021-03-06 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0007_auto_20210306_1643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workexperience',
            old_name='positon',
            new_name='position',
        ),
    ]
