# Generated by Django 3.1.7 on 2021-03-06 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0008_auto_20210306_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='positon',
            new_name='degree',
        ),
    ]
