# Generated by Django 3.1.7 on 2021-03-06 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0009_auto_20210306_2004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='Age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='Phone',
            new_name='phone',
        ),
    ]
