# Generated by Django 3.1.7 on 2021-03-06 20:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0010_auto_20210306_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('organisation', models.CharField(max_length=50)),
                ('date_acheived', models.DateField(default=datetime.date(2021, 3, 6))),
                ('score', models.TextField(max_length=5000)),
            ],
        ),
    ]
