# Generated by Django 3.1.6 on 2021-03-09 20:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0011_certification'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='date_acheived',
            field=models.DateField(default=datetime.date(2021, 3, 9)),
        ),
        migrations.AlterField(
            model_name='education',
            name='date_ended',
            field=models.DateField(blank=True, default=datetime.date(2021, 3, 9), null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='date_started',
            field=models.DateField(default=datetime.date(2021, 3, 9)),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='date_ended',
            field=models.DateField(blank=True, default=datetime.date(2021, 3, 9), null=True),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='date_started',
            field=models.DateField(default=datetime.date(2021, 3, 9)),
        ),
    ]
