# Generated by Django 3.1.6 on 2021-03-09 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0012_auto_20210309_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='first_function',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='second_function',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
